name: ast-firmware

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  ast-firmware:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/ast-firmware.git
      repoPkg: ast-firmware
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
