name: chiaki-git

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  chiaki-git:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/chiaki-git.git
      repoPkg: chiaki
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
