name: dropbox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  dropbox:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/dropbox.git
      repoPkg: dropbox
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
