name: dropbox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  dropbox:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/dropbox.git
      repoPkg: dropbox
      recvKeys: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
