name: flow_proton-ge-custom

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  main_psautohint:
    name: Run psautohint
    uses: highkeep/aur/.github/workflows/psautohint.yml@main
  generic_psautohint:
    name: Run psautohint
    uses: highkeep/aur/.github/workflows/psautohint.yml@main
    with:
      ref: generic
  main_python-ufonormalizer:
    name: Run python-ufonormalizer
    needs: main_psautohint
    uses: highkeep/aur/.github/workflows/python-ufonormalizer.yml@main
  generic_python-ufonormalizer:
    name: Run python-ufonormalizer
    needs: generic_psautohint
    uses: highkeep/aur/.github/workflows/python-ufonormalizer.yml@main
    with:
      ref: generic
  main_afdko:
    name: Run afdko
    needs: main_python-ufonormalizer
    uses: highkeep/aur/.github/workflows/afdko.yml@main
  generic_afdko:
    name: Run afdko
    needs: generic_python-ufonormalizer
    uses: highkeep/aur/.github/workflows/afdko.yml@main
    with:
      ref: generic
  main_lib32-lzo:
    name: Run lib32-lzo
    needs: main_afdko
    uses: highkeep/aur/.github/workflows/lib32-lzo.yml@main
  generic_lib32-lzo:
    name: Run lib32-lzo
    needs: generic_afdko
    uses: highkeep/aur/.github/workflows/lib32-lzo.yml@main
    with:
      ref: generic
  main_mingw-w64-tools:
    name: Run mingw-w64-tools
    needs: main_lib32-lzo
    uses: highkeep/aur/.github/workflows/mingw-w64-tools.yml@main
  generic_mingw-w64-tools:
    name: Run mingw-w64-tools
    needs: generic_lib32-lzo
    uses: highkeep/aur/.github/workflows/mingw-w64-tools.yml@main
    with:
      ref: generic
  main_proton-ge-custom:
    name: Run proton-ge-custom
    needs: [main_afdko,main_lib32-lzo,main_mingw-w64-tools]
    uses: highkeep/aur/.github/workflows/proton-ge-custom.yml@main
  generic_proton-ge-custom:
    name: Run proton-ge-custom
    needs: [generic_afdko,generic_lib32-lzo,generic_mingw-w64-tools]
    uses: highkeep/aur/.github/workflows/proton-ge-custom.yml@main
    with:
      ref: generic
