name: flow_paru-bin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  generic_paru-bin:
    name: Run paru-bin using generic_x86_64
    uses: highkeep/aur/.github/workflows/paru-bin.yml@main
    with:
      ref: generic
