name: flow_proton

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  main_proton:
    name: Run proton using alderlake
    uses: highkeep/aur/.github/workflows/proton.yml@main
  generic_proton:
    name: Run proton using generic_x86_64
    uses: highkeep/aur/.github/workflows/proton.yml@main
    with:
      ref: generic
