name: flow_gwe

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */3 * *'

jobs:
  python-py3nvml:
    name: Run python-py3nvml
    uses: highkeep/aur/.github/workflows/python-py3nvml.yml@generic
  python-injector:
    name: Run python-injector
    needs: python-py3nvml
    uses: highkeep/aur/.github/workflows/python-injector.yml@generic
  gwe:
    name: Run gwe
    needs: [python-py3nvml,python-injector]
    uses: highkeep/aur/.github/workflows/gwe.yml@generic
