name: flow_proton-ge-custom

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  main_psautohint:
    name: Run psautohint using alderlake
    uses: highkeep/aur/.github/workflows/psautohint.yml@main
  main_python-ufonormalizer:
    name: Run python-ufonormalizer using alderlake
    needs: main_psautohint
    uses: highkeep/aur/.github/workflows/python-ufonormalizer.yml@main
  main_afdko:
    name: Run afdko using alderlake
    needs: main_python-ufonormalizer
    uses: highkeep/aur/.github/workflows/afdko.yml@main
  main_lib32-lzo:
    name: Run lib32-lzo using alderlake
    needs: main_afdko
    uses: highkeep/aur/.github/workflows/lib32-lzo.yml@main
  main_mingw-w64-tools:
    name: Run mingw-w64-tools using alderlake
    needs: main_lib32-lzo
    uses: highkeep/aur/.github/workflows/mingw-w64-tools.yml@main
  main_proton-ge-custom:
    name: Run proton-ge-custom using alderlake
    needs: [main_afdko,main_lib32-lzo,main_mingw-w64-tools]
    uses: highkeep/aur/.github/workflows/proton-ge-custom.yml@main
  generic_psautohint:
    name: Run psautohint using generic_x86_64
    uses: highkeep/aur/.github/workflows/psautohint.yml@main
    with:
      ref: generic
  generic_python-ufonormalizer:
    name: Run python-ufonormalizer using generic_x86_64
    needs: generic_psautohint
    uses: highkeep/aur/.github/workflows/python-ufonormalizer.yml@main
    with:
      ref: generic
  generic_afdko:
    name: Run afdko using generic_x86_64
    needs: generic_python-ufonormalizer
    uses: highkeep/aur/.github/workflows/afdko.yml@main
    with:
      ref: generic
  generic_lib32-lzo:
    name: Run lib32-lzo using generic_x86_64
    needs: generic_afdko
    uses: highkeep/aur/.github/workflows/lib32-lzo.yml@main
    with:
      ref: generic
  generic_mingw-w64-tools:
    name: Run mingw-w64-tools using generic_x86_64
    needs: generic_lib32-lzo
    uses: highkeep/aur/.github/workflows/mingw-w64-tools.yml@main
    with:
      ref: generic
  generic_proton-ge-custom:
    name: Run proton-ge-custom using generic_x86_64
    needs: [generic_afdko,generic_lib32-lzo,generic_mingw-w64-tools]
    uses: highkeep/aur/.github/workflows/proton-ge-custom.yml@main
    with:
      ref: generic