name: flow_gwe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  main_python-py3nvml:
    name: Run python-py3nvml
    uses: highkeep/aur/.github/workflows/python-py3nvml.yml@main
  generic_python-py3nvml:
    name: Run python-py3nvml
    uses: highkeep/aur/.github/workflows/python-py3nvml.yml@generic
  main_python-injector:
    name: Run python-injector
    needs: main_python-py3nvml
    uses: highkeep/aur/.github/workflows/python-injector.yml@main
  generic_python-injector:
    name: Run python-injector
    needs: generic_python-py3nvml
    uses: highkeep/aur/.github/workflows/python-injector.yml@generic
  main_gwe:
    name: Run gwe
    needs: [main_python-py3nvml,main_python-injector]
    uses: highkeep/aur/.github/workflows/gwe.yml@main
  generic_gwe:
    name: Run gwe
    needs: [generic_python-py3nvml,generic_python-injector]
    uses: highkeep/aur/.github/workflows/gwe.yml@generic
