name: gitkraken

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,19 * * *'

jobs:
  gitkraken:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/gitkraken.git
      repoPkg: gitkraken
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
