name: grimblast-git

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  grimblast-git:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/grimblast-git.git
      repoPkg: grimblast-git
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
