name: _gwe

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ""
      force:
        type: boolean
        default: false
      commit:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: ""
      force:
        type: boolean
        default: false
      commit:
        type: boolean
        default: true

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      ref: ${{ inputs.ref }}
      repo_url: https://aur.archlinux.org
      repo_pkg: gwe
      nvidiaUtils: true