name: gwe

env:
  art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 */3 * *'

jobs:
  python-py3nvml:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@testing
    with:
      repoUrl: https://aur.archlinux.org/python-py3nvml.git
      repoPkg: python-py3nvml
      nvidiaUtils: true
      art: ${{ env.art }}
  python-injector:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@testing
    with:
      repoUrl: https://aur.archlinux.org/python-injector.git
      repoPkg: python-injector
      nvidiaUtils: true
      art: ${{ env.art }}
  gwe:
    needs: [python-py3nvml, python-injector]
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@testing
    with:
      repoUrl: https://aur.archlinux.org/gwe.git
      repoPkg: gwe
      nvidiaUtils: true
      art: ${{ env.art }}