name: ombi

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  openssl-1_0:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/openssl-1.0.git
      repoPkg: openssl-1.0
      makepkgArgs: --skippgpcheck
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  ombi:
    needs: openssl-1_0
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/ombi.git
      repoPkg: ombi
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
