name: paru-bin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,19 * * *'

jobs:
  paru-bin:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/paru-bin.git
      repoPkg: paru-bin
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
