name: pkg_act

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: ""
  schedule:
    - cron: '0 */6 * * *'

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      ref: ${{ inputs.ref }}
      repo_url: https://aur.archlinux.org
      repo_pkg: act