name: pkg_brave

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: $GITHUB_REF_NAME
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      repo_url: https://aur.archlinux.org
      repo_pkg: brave
      multilib: true