name: pkg_wine-ge-custom

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      repo_url: https://aur.archlinux.org
      repo_pkg: wine-ge-custom
      nvidiaUtils: true