name: pkg_paru-bin

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: $GITHUB_REF_NAME
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      repo_url: https://aur.archlinux.org
      repo_pkg: paru-bin