name: _proton-ge-custom

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ""
  workflow_dispatch:

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      ref: ${{ inputs.ref }}
      repo_url: https://aur.archlinux.org
      repo_pkg: proton-ge-custom
      nvidiaUtils: true