name: proton-ge-custom-flow

on:
  workflow_dispatch:

jobs:
  psautohint:
    name: Run psautohint
    uses: highkeep/aur/.github/workflows/psautohint.yml@main
  python-ufonormalizer:
    name: Run python-ufonormalizer
    uses: highkeep/aur/.github/workflows/python-ufonormalizer.yml@main
  afdko:
    name: Run afdko
    needs: [psautohint,python-ufonormalizer]
    uses: highkeep/aur/.github/workflows/afdko.yml@main
  mingw-w64-tools:
    name: Run mingw-w64-tools
    uses: highkeep/aur/.github/workflows/mingw-w64-tools.yml@main
  lib32-lzo:
    name: Run lib32-lzo
    needs: python-ufonormalizer
    uses: highkeep/aur/.github/workflows/lib32-lzo.yml@main
  proton-ge-custom:
    name: Run proton-ge-custom
    needs: [afdko,mingw-w64-tools,lib32-lzo]
    uses: highkeep/aur/.github/workflows/proton-ge-custom.yml@main
