name: psautohint

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update Submodules
      run: |
        git submodule update --remote
    - name: Makepkg Build and Check
      id: makepkg
      uses: highkeep/pkgbuild-action@master
      with:
        pkgdir: "psautohint"
        pacmanConf: "configs/alderlake_pacman.conf"
        makepkgConf: "configs/alderlake_makepkg.conf"
        repoReleaseTag: "alderlake"
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "Package: ${{ steps.makepkg.outputs.repofile0 }}"
        echo "Package: ${{ steps.makepkg.outputs.repofile1 }}"
        echo "Package: ${{ steps.makepkg.outputs.repofile2 }}"
        echo "Package: ${{ steps.makepkg.outputs.repofile3 }}"
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: alderlake
        file: ${{ steps.makepkg.outputs.pkgfile0 }}
        overwrite: true
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: alderlake
        file: ${{ steps.makepkg.outputs.repofile0 }}
        overwrite: true
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: alderlake
        file: ${{ steps.makepkg.outputs.repofile1 }}
        overwrite: true
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: alderlake
        file: ${{ steps.makepkg.outputs.repofile2 }}
        overwrite: true
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: alderlake
        file: ${{ steps.makepkg.outputs.repofile3 }}
        overwrite: true