name: _python-py3nvml

on:
  workflow_call:

jobs:
  process:
    uses: highkeep/aur/.github/workflows/template_aur.yml@main
    with:
      repo_url: https://aur.archlinux.org
      repo_pkg: python-py3nvml
      nvidiaUtils: true