name: slack-desktop

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,19 * * *'

jobs:
  slack-desktop:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.2
    with:
      repoUrl: https://aur.archlinux.org/slack-desktop.git
      repoPkg: slack-desktop
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
