name: python-ufonormalizer

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Clone Package
      run: |
        git clone https://aur.archlinux.org/${{ github.workflow }}.git