name: tester

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      repo_pkg:
        required: true
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      ref:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      repo_url:
        type: string
      repo_pkg:
        type: string
      makepkgArgs:
        type: string
      multilib:
        type: boolean
        default: false
      nvidiaUtils:
        type: boolean
        default: false
      ref:
        type: string
        default: ""

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: set ref
        id: ref
        run: |
          input_ref=${{ inputs.ref }}
          echo "ref=${input_ref:-main}" >> $GITHUB_OUTPUT
      - name: echo
        run: |
          echo ${{ github.event.inputs.repo_url }} ${{ inputs.repo_url }}
          echo ${{ github.event.inputs.repo_pkg }} ${{ inputs.repo_pkg }}
          echo ${{ github.event.inputs.makepkgArgs }} ${{ inputs.makepkgArgs }}
          echo ${{ github.event.inputs.multilib }} ${{ inputs.multilib }}
          echo ${{ github.event.inputs.nvidiaUtils }} ${{ inputs.nvidiaUtils }}
          echo ${{ github.event.inputs.ref }} ${{ inputs.ref }}
          echo ${{ steps.ref.outputs.ref }}