name: python-ufonormalizer

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Clone Package
      run: |
        remoteVersion=$(git ls-remote -q https://aur.archlinux.org/${{ github.workflow }}.git heads/master | cut -f1)
        currentVersion=$(cat versions/${{ github.workflow }} 2>/dev/null)
        echo ${remoteVersion} ${currentVersion}
    - name: Update Version
      run: |
        echo $(git ls-remote ${{ github.workflow }} heads/master) > versions/${{ github.workflow }}
        cat versions/${{ github.workflow }}