name: python-ufonormalizer

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Clone Package
      run: |
        echo `git ls-remote -q https://aur.archlinux.org/${{ github.workflow }}.git heads/master | cut -f1`
        echo `cat versions/${{ github.workflow }} 2>/dev/null`
        ls -l
    - name: Update Version
      run: |
        ls -l
        echo `git -C ${{ github.workflow }} rev-parse HEAD` > versions/${{ github.workflow }}
        cat versions/${{ github.workflow }}