name: upd72020x-fw

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  upd72020x-fw:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/upd72020x-fw.git
      repoPkg: upd72020x-fw
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
