name: wlogout-git

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  wlogout-git:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/wlogout-git.git
      repoPkg: wlogout-git
      updateSrcInfo: true
      multilib: true
      recvKeys: E25D679AF73C6D2F
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
