name: xdg-desktop-portal-hyprland-git

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  xdg-desktop-portal-hyprland-git:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/xdg-desktop-portal-hyprland-git.git
      repoPkg: xdg-desktop-portal-hyprland-git
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
