name: yuzu-early-access

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  cubeb:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/cubeb.git
      repoPkg: cubeb
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  xbyak:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/xbyak.git
      repoPkg: xbyak
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  dynarmic:
    needs: [xbyak]
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/dynarmic.git
      repoPkg: dynarmic
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  discord-rpc:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/discord-rpc.git
      repoPkg: discord-rpc
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  cpp-httplib:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/cpp-httplib.git
      repoPkg: cpp-httplib
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
  yuzu-early-access:
    needs: [cubeb, dynarmic, discord-rpc, cpp-httplib]
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/yuzu-early-access.git
      repoPkg: yuzu-early-access
      nvidiaUtils: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
