name: yuzu-early-access

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  yuzu-early-access:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.4
    with:
      repoUrl: https://aur.archlinux.org/yuzu-early-access.git
      repoPkg: yuzu-early-access
      multilib: true
      art: '[{"architecture":"alderlake", "repoTag":"alderlake"},{"architecture":"generic", "repoTag":"generic_x86_64"}]'
