name: zoom

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,19 * * *'

jobs:
  zoom:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.3
    with:
      repoUrl: https://aur.archlinux.org/zoom.git
      repoPkg: zoom
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
