name: zoom

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'

jobs:
  zoom:
    uses: highkeep/pkgbuild/.github/workflows/multiarch_builder.yml@v2.1
    with:
      repoUrl: https://aur.archlinux.org/zoom.git
      repoPkg: zoom
      art: '[{"architecture":"generic", "repoTag":"generic_x86_64"}]'
